// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qpyblcwvpqemuagqinfy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFweWJsY3d2cHFlbXVhZ3FpbmZ5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU5NDQyMzIsImV4cCI6MjA3MTUyMDIzMn0.spMjZZXBUX0_93jtFVUU3O7VBcZigO8v9AHN_CQOHbM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});