// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eynjoddkvooapeiyuupm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV5bmpvZGRrdm9vYXBlaXl1dXBtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwMDE0NDQsImV4cCI6MjA2NTU3NzQ0NH0.Bu_q3hpt4uqmJAO1h1ZbUtGQFh_Y-ma36i1YBYx_VYc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});