// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://swxbydfypyojcerentsz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN3eGJ5ZGZ5cHlvamNlcmVudHN6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc3NzY1MjgsImV4cCI6MjA2MzM1MjUyOH0.0_MBDwilFQfz3ofrYaT21Jk2fQ9F1uLJ-MtgkhzBtHI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});